version: '3.3'

volumes:
  postgres_data:
  static_volume:
  nginx:

services:
  db:
    image: postgres:13.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    build: .
    container_name: web
    restart: always
    command: gunicorn statistic_counter.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static/
      - nginx:/code/nginx/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - static_volume:/static/
      - nginx:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - web